### ISSUE TITLE
App::BatParser has no version

### ISSUE THREAD

**Issue by eserte** [pablrod/App-BatParser#2]
When looking at a fail report of Bat-Interpreter-0.007 one can see:
```
------------------------------
PREREQUISITES
------------------------------

Prerequisite modules loaded:

requires:

    Module               Need  Have    
    -------------------- ----- --------
    App::BatParser       0     0       
...
```

So there's no version available for App::BatParser. I suspect that the Bat-Interpreter failures are caused by older versions of App::BatParser, but as there's no version available, I cannot tell. And it would not be possible to specify the minimum required version.

**Comment by pablrod** [comment]
Thank you for pointing this out!

**Comment by pablrod** [comment]
Starting with version [0.005](https://github.com/pablrod/App-BatParser/releases/tag/v0.005) there is a `$App::BatParser::VERSION` correctly defined. 
So [Bat::Interpreter](https://metacpan.org/pod/Bat::Interpreter) requires the correct version of [App::BatParser](https://metacpan.org/pod/App::BatParser) (0.005 actually).
